### ISSUE TITLE
Installation Steps and Checks

### ISSUE THREAD

**Issue by RRMaximiliano** [dime-worldbank/googletraffic#5]
From a fresh R and Rstudio install I got the following:

![image](https://user-images.githubusercontent.com/7269831/192432772-7e7c1bfc-ac49-4fd3-8d49-83709dde07aa.png)

I had to install `googleway`, `plotwidgets`, `sf`, 

Warning message: 

![image](https://user-images.githubusercontent.com/7269831/192433121-2203f84c-f79c-474e-9ca3-e706d615ca16.png)

I got this error after running the first part:

![image](https://user-images.githubusercontent.com/7269831/192433378-65ae33c2-c303-4053-a2f7-42a10a46d4c6.png)

So, I had to install webshot.

After the second run, I got this which are only warning messages:

![image](https://user-images.githubusercontent.com/7269831/192433534-95002262-f8a7-4627-93ff-05cde8852d32.png)

I can still get the ggplot after getting the above message, but I wanted to share what I got.

![image](https://user-images.githubusercontent.com/7269831/192433643-f5f01bba-2555-447d-9ccf-7a1f381cd415.png)

The same happens when I use the examples in the vignette.

I will continue looking and running more examples tomorrow.

**Comment by ramarty** [comment]
Super helpful, thanks! Looks like installing the package isn't actually installing the dependency packages -- will look into / fix this.
